---
  - name: 'common: install python-apt'
    raw: 'apt-get install -y python-apt'
    tags: common

  - name: 'common: update apt package cache'
    apt: update_cache=yes
    tags: common

  - name: 'common: update apt'
    apt: upgrade=yes
    tags: common

  - name: 'install packages'
    action: apt pkg=$item state=present
    with_items:
      - nginx
      - redis-server
      - haproxy
      - uwsgi
      - uwsgi-plugin-python

  - name: 'haproxy: set enabled to 1'
    action: lineinfile dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
